{% set name = "Orange3-Geo" %}
{% set version = "0.3.0" %}
{% set sha256 = "97e9459e2b1a0153a06dd7740475615eb21c6fa147301ebb217447c3a4866c2c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - orange3 >=3.25.0
    - scikit-learn
    - pandas
    - scipy >=0.17
    - shapely
    - simplejson
    - pillow

test:
  imports:
    - orangecontrib.geo

about:
  home: http://github.com/biolab/orange3-geo
  license: GPL-3.0-only
  license_file: LICENSE.txt
  summary: Orange add-on for dealing with geography and geo-location
  dev_url: http://github.com/biolab/orange3-geo

extra:
  recipe-maintainers:
    - jakakokosar
    - lanzagar
    - robertcv
    - vesnaT
    - primozgodec
